#lang racket
(struct assignment (var value) #:transparent #:mutable)
(struct nterm              ()              #:transparent #:mutable)
(struct node     nterm     (tokens value ) #:transparent #:mutable)
(struct E        node      ()              #:transparent #:mutable)
(struct operator node      ()              #:transparent #:mutable)
(struct Un       operator  ()              #:transparent #:mutable)
(struct Op1      operator  ()              #:transparent #:mutable)
(struct Op2      operator  ()              #:transparent #:mutable)
(struct Op3      operator  ()              #:transparent #:mutable)
(struct Op4      operator  ()              #:transparent #:mutable)
(struct Op5      operator  ()              #:transparent #:mutable)
(struct fold     node      (acc tok)       #:transparent #:mutable)
(struct Pr       node      ()              #:transparent #:mutable)
(struct E1       node      ()              #:transparent #:mutable)
(struct C1       fold      ()              #:transparent #:mutable)
(struct E2       node      ()              #:transparent #:mutable)
(struct C2       fold      ()              #:transparent #:mutable)
(struct E3       node      ()              #:transparent #:mutable)
(struct C3       fold      ()              #:transparent #:mutable)
(struct E4       node      ()              #:transparent #:mutable)
(struct C4       fold      ()              #:transparent #:mutable)
(struct E5       node      ()              #:transparent #:mutable)
(struct C5       fold      ()              #:transparent #:mutable)
(struct parse-result nterm (value)         #:transparent #:mutable)

(struct token (pos text)                   #:transparent #:mutable)
(struct end-of-input token       ()        #:transparent #:mutable)
(struct op-token     token       ()        #:transparent #:mutable)
(struct op-sub       op-token    ()        #:transparent #:mutable)
(struct op-mul       op-token    ()        #:transparent #:mutable)
(struct op-div       op-token    ()        #:transparent #:mutable)
(struct op-add       op-token    ()        #:transparent #:mutable)
(struct op-assign    op-token    ()        #:transparent #:mutable)
(struct number       token       (value)   #:transparent #:mutable)
(struct variable     token       ()        #:transparent #:mutable)
(struct open-paren   token       ()        #:transparent #:mutable)
(struct close-paren  token       ()        #:transparent #:mutable)
(struct violation    token       ()        #:transparent #:mutable)

(provide (all-defined-out))
